name: CI - Microservicio Programas
on:
  push:
    paths:
      - 'microservicio-programas/**'
      - '.github/workflows/ms-programas.yml'
    branches:
      - main
  pull_request:
    paths:
      - 'microservicio-programas/**'
      - '.github/workflows/ms-programas.yml'
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: microservicio-programas # Directorio de trabajo por defecto para los 'run'

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # --- PASO DE DEBUG: VERIFICAR ARCHIVOS ---
      - name: Listar archivos en el directorio de trabajo actual
        run: |
          echo "Directorio actual:"
          pwd
          echo "Contenido del directorio actual:"
          ls -la
          echo "Contenido recursivo desde la raíz del repositorio:"
          ls -R /home/runner/work/${{ github.repository }}/${{ github.repository }}
      # --- FIN PASO DE DEBUG ---

      - name: Instalar dependencias # Este es el paso que falla
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Esto busca requirements.txt en el working-directory

      - name: Ejecutar tests
        run: pytest --maxfail=1 --disable-warnings -v